
export const newtab = {
    '--newtab-background-color': '#000',
    '--app-background-color': 'rgba(0, 0, 0, .4)',
    '--app-width-size': '560px',
    '--search-input-height': '64px',
    '--search-input-value-text-color': '#fafafa',
    '--search-input-value-text-size': '26px',
    '--search-results-height': '432px',
    '--search-results-scrollbar-width': '2px',
    '--search-results-scrollbar-color': 'rgba(0, 0, 0, 0.5)',
    '--selected-suggestion-background-color': 'rgba(0, 0, 0, 0.2)',
    '--selected-suggestion-title-text-color': '#fff',
    '--selected-suggestion-subtitle-text-color': '#ccc',
    '--highlighted-suggestion-text-color': '#fabb2d',
    '--suggestion-border-color': 'rgba(209, 209, 209, .1)',
    '--suggestion-height': '48px',
    '--suggestion-title-text-color': '#eee',
    '--suggestion-title-text-size': '16px',
    '--suggestion-title-text-weight': '300',
    '--suggestion-subtitle-text-color': '#bbb',
    '--suggestion-subtitle-text-size': '12px',
    '--suggestion-subtitle-text-style': "PingFangSC-Light"
}

export const page = {
    '--app-background-color': '#fff',
    '--app-width-size': '500px',
    '--search-input-height': '50px',
    '--search-input-value-text-color': '#000',
    '--search-input-value-text-size': '22px',
    '--search-results-height': '400px',
    '--search-results-scrollbar-width': '2px',
    '--search-results-scrollbar-color': 'rgba(0, 0, 0, 0.5)',
    '--selected-suggestion-background-color': 'rgb(209, 209, 209)',
    '--selected-suggestion-title-text-color': '#000',
    '--selected-suggestion-subtitle-text-color': '#000',
    '--highlighted-suggestion-text-color': 'red',
    '--suggestion-height': '44px',
    '--suggestion-border-color': 'rgba(209, 209, 209, .1)',
    '--suggestion-title-text-color': '#000',
    '--suggestion-title-text-size': '14px',
    '--suggestion-title-text-weight': '400',
    '--suggestion-subtitle-text-color': '#000',
    '--suggestion-subtitle-text-size': '12px',
    '--suggestion-subtitle-text-style': 'inherit'
}

export const popup = {
    '--app-background-color': '#fff',
    '--app-width-size': '500px',
    '--search-input-height': '50px',
    '--search-input-value-text-color': '#000',
    '--search-input-value-text-size': '22px',
    '--search-results-height': '400px',
    '--search-results-scrollbar-width': '2px',
    '--search-results-scrollbar-color': 'rgba(0, 0, 0, 0.5)',
    '--selected-suggestion-background-color': 'rgb(209, 209, 209)',
    '--selected-suggestion-title-text-color': '#000',
    '--selected-suggestion-subtitle-text-color': '#000',
    '--highlighted-suggestion-text-color': 'red',
    '--suggestion-height': '44px',
    '--suggestion-border-color': 'rgba(209, 209, 209, .1)',
    '--suggestion-title-text-color': '#000',
    '--suggestion-title-text-size': '14px',
    '--suggestion-title-text-weight': '400',
    '--suggestion-subtitle-text-color': '#000',
    '--suggestion-subtitle-text-size': '12px',
    '--suggestion-subtitle-text-style': 'inherit'
}